### ISSUE TITLE
Weird behavior when flipping card

### ISSUE THREAD

**Issue by fedxgibson** [arunahuja94/react-native-credit-card-input-view#1]
Hi! 

Thanks so much for this component!

What I notice is that when the card is flipped, it does not show the back image immediately. It shows the front image reversed, and then it changes to the back. Do you know if I need to install some animation library? 

Thanks!

**Comment by fedxgibson** [comment]
Closing, after running the application in production mode, the animation are smoother.

**Comment by arunahuja94** [comment]
yes delay only occurs sometimes while debugging
